language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: ciYSJc+FW3L14dl0FlETFw+ZmNHE1ArzwgPgrx9xVsIk4VoNQdA/UMRyx2mpGxPQ3gvSsGc7QAAb8IIXW+ZfJw5Daz8a06XmdNHIRElzm2S5NXUwgs0l7GjH8HPpw6bJi4TN0GRQ0DPX4pnpYZwa/rWWffSkbO+z5umSmdpApiEoMW7DL5S957s0E4LY8EpCuBbRSIrC2M7cHhHYz0m+Si+KVes2IT9SmPyEJ1xLjaVLnim0c0gLKxtMaRyBbcXYUePGlb/7iGT7w4MhFb44BE5LyxH4poLBwkA3im8wjcXGdD9bRMjeSrGhQnwAAdmDg2QxOmKymfnroeq6pcTFt5uuDAvY334+HrGa95pK8hABLI1tPBAKn+0bR6vFgAI9rIHMNp6Cbr69wWHWBNY0/dxwXevw8POOVSCJ8PsZwAKMkjR38tC5Ey9bFT+VEpAY/Wk6Hd4ylMPwYyVCwPOSS+5BV+M45HZoSp6QZF4gQywbFYBOfpUT3U1EgVJRCCrRfubxhb7kPUmhLTcIJr8r3GfecpTAqjcQ7QAxJvr4nEk009qmoJT0LEFXIY78RlFs9gtDn7fIWp4lgnmZpZSiGM2YYR64RWSfwnuwW25RDQ3ICFiL68YQPkHLECuP8rZ4anuSLKhGS1RTtKCR8+kJi78lU5EjUCIr+f/k7L8UdPA=
    app: franksorder