language: java
jdk:
- oraclejdk8
deploy:
    provider: heroku
    api_key:
        secure: Z/VC0S2Z9UbWDVqmL08DEgTlb/0pIukPk5xVP5j9aeQntXSmIIsicwCy6yH18YQfRKzayz3ttxGUP6u6TBVQlUAWG97DiXD1QAt3kLLT+gSUeYQ64dQTkyi6CF9gptinVaG+4dh7+4jSNZmTWkkJPCOZsK4Tki6QFBVGQD1oXaolkTDFuOGBDcDyJke0kR5ELtHZgig7oCEXmTdSw2XX1BfnbsQ4bwHtALxGQmCAWkZxysHEESvDPWpLfxaH4v+XzY47xwcwYYk/oj9arVa6esgBN1q+a/6Lnks6YQYUPuRKsJEY+vYHBowNHOLjoZCsCqjCFIrbUrfOa3mieKC8Mt2CZhg5ON5PJA8OMeddW04fYtrS24HY4KdtFlvahsCUTCjqTO0uUuHAgZ61otWLJqnZjLcOGOdSNm1lNEPBwzBv0IPxt8eP3u1DNlog2PNegQd9p2W5ghrPA04wqBTBhyrvIbXYVen95OijVJqM2AzkKHRVCGCT0jRz5XpiaOI0OJyljjloXTQA9Ul8gZAxgORBv+js4iJNGINVNWWHCoGZL9XeWrKbsxvL3Ol4bCbpzBj1wq+DU2BX2vU73Azo6tD8OBXXt5s9ot6csRUFOwzuod31yHUIWZfrel4Z+dvUz+s1aMsSnvDNV4SPokjXUKyg4JqUupxheBZSozQj39k=
    app: franksorder